### ISSUE TITLE
Make body output optional?

### ISSUE THREAD

**Issue by p1ho** [zrrrzzt/html-validator#128]
Hello!

I finally got around to implementing isLocal we discussed for `site-validator-cli`,
I got it working, but it always outputs the body text it sends to the w3c-validator in the console.
It's probably because of [this](https://github.com/zrrrzzt/html-validator/blob/572d7130b2c82fc2128aea739a16f32f01ead1ed/lib/get-data.js#L9). I can see it being useful, but right now there's no way to turn it off.

If needed I can submit a PR

**Comment by zrrrzzt** [comment]
Seems to me like this is a console log that should be removed.

I'll update it right away.
