### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by RyanPWalker** [zrrrzzt/html-validator#164]
I'm using html-validator in my jest tests.  Everything has worked fine up until recently html-validator always hits my `catch` block and displays the error:
```
{ Error: self signed certificate in certificate chain
          at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
          at TLSSocket.emit (events.js:198:13)
          at TLSSocket._finishInit (_tls_wrap.js:636:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
```

package.json:
```
    "html-validator": "^4.1.1",
    "jest": "^24.8.0",
```
node version: `10.16.3`

code:
```
const html = '<div>hello world</div>'
const options = {
            data: html,
            format: 'html',
            isFragment: true,
            ignore: [
                'Error: Attribute “ariahaspopup” not allowed on element “span” at this point.',
                'Error: Element “style” not allowed as child of element “span” in this context. 
(Suppressing further errors from this subtree.)',
                'Error: self signed certificate in certificate chain'
            ]
        };

        try {
            const result = await validator(options);

            console.info(result);
            expect(result).toBe('The document validates according to the specified schema(s).');
        } catch (error) {
            console.error(error);
        }
```

I've tried:
-`yarn cache clean`
-removing yarn.lock and node modules and reinstalling

**Comment by zrrrzzt** [comment]
Not sure this is related to this module. Looks more like an issue with the certificate chain.

You can add this at the top of you test-file and probably skip the certificate error.

```
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;
```

Warning: This is not a setting you use in production.

**Comment by RyanPWalker** [comment]
You sure it's not related?  I'm only trying to validate a local html string, I'm not trying to make any http calls.  Seems like the module is trying to make an http request?

**Comment by zrrrzzt** [comment]
If I run the code without the testrunner parts.

```JavaScript
(async () => {
  const validator = require('html-validator')
  const html = '<div>hello world</div>'
  const options = {
    data: html,
    format: 'html',
    isFragment: true,
    ignore: [
      'Error: Attribute “ariahaspopup” not allowed on element “span” at this point.',
      'Error: self signed certificate in certificate chain'
    ]
  }
  try {
    const result = await validator(options)
    console.info(result)
  } catch (error) {
    console.error(error)
  }
})()
```

Returns

```
$ The document validates according to the specified schema(s).
```

So at least not the module by itself seems the be the problem.

**Comment by zrrrzzt** [comment]
To be clear: The example code works on my machine :-) If it still fails for you there might be other factors to look at.

Regarding http calls: this module will do a call to https://validator.w3.org/nu/ where the validation is done.

**Comment by RyanPWalker** [comment]
Using `process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;` didn't skip the error, I'll keep looking into ways to skip it.  It was working before this last month so I'm not sure whether or not it's an issue with the certificate chain.

That url doesn't seem to be blocked or have any errors coming from my company's firewall as far as I can tell.  Not sure what could be the issue then.

**Comment by zrrrzzt** [comment]
Never fun when this happens. Very hard to debug.

Are you able to run your tests in another environment like GitHub with GitHub Actions or is the code only available in a private repo? I could run the tests myself if the code is public somewhere.

**Comment by PlNG** [comment]
@RyanPWalker See if setting the environment variable
`set NODE_EXTRA_CA_CERTS=/path/to/your/cert.file`
solves your issue

If you don't know / can't figure out where the certificate is, speak to your company's IT department, it's probably a MITM cert that they manage so that the firewall can inspect the stream contents and they'll be able to provide a path. Let us know so that zrrrzzt can close out the issue.

**Comment by RyanPWalker** [comment]
Thanks for your inputs, I've tried many things and still can't get past the error.

Just going to close this as it's probably specific to my company's firewall/network and not this npm.
