### ISSUE TITLE
Access page with htaccess login

### ISSUE THREAD

**Issue by fedojo** [zrrrzzt/html-validator#17]
Hi!
How can I access the page with htaccess login and pass?
Ive tried http://login:pass@domain but it doesnt work.
Is there any other option todo this operation?
Kind regards

**Comment by zrrrzzt** [comment]
This module does not support login/pass other than the way you have described.

What you can do as an alternative is to retrieve the page and send the data to this module for validation.

If you are familiar with cli and tools like curl I would recommend to use [html-validator-cli](https://www.npmjs.com/package/html-validator-cli)

Example with file

```sh
curl -u "username:password" -s http://you-url.com > data.html && html-validator --file=data.html
```

Example with data

```sh
DATA=$(curl -u "username:password" -s http://your-url.com) && html-validator --data="$DATA"
```

Hope this helps.
