### ISSUE TITLE
Can't Find ./lib/whatwg-elements.json

### ISSUE THREAD

**Issue by spencerfai** [zrrrzzt/html-validator#186]
**Error message:** 
Using the new WHATWG mode, I get:

`Failed to load elements from "./lib/whatwg-elements.json": Cannot find module './lib/whatwg-elements.json'`

This appears to be triggered on line 2 of whatwg-standard-config.js:
`  elements: ['html5', './lib/whatwg-elements.json'],`

Removing the reference to the JSON file cleans it up, but then, of course, we lose what's in the JSON. 

Thanks!

**Comment by zrrrzzt** [comment]
Thank you! Fixed in version 5.1.1

**Comment by zrrrzzt** [comment]
ooops. it was not fixed

I'll be back

**Comment by zrrrzzt** [comment]
5.1.2 fixed and verified.

**Comment by spencerfai** [comment]
Super! Thanks for the rapid fix!

One minor niggle - I think the `requiredAttribute` key is supposed to be `requiredAttributes`? https://html-validate.org/usage/elements.html. 

Thanks again for your work on this.
