### ISSUE TITLE
validator.w3.org/nu ip blocked errors are not handled

### ISSUE THREAD

**Issue by danpaz** [zrrrzzt/html-validator#2]
Thanks for this helpful module!

We recently bumped up against the rate limit for the validator.w3.org/nu which [is cited as 500 requests within a 10-minute interval](http://www.w3.org/Help/abuse-info/re-reqs.html), causing us to receive a 403 response from the api. However it took us some time to debug this because the relevant code [here](https://github.com/zrrrzzt/html-validator/blob/master/index.js#L50-L60) does not handle the 403 response.

When the rate limit is hit, the `error` from the request is null and the `result` is an HTML error page. On L56, if the format option is specified as json, the module tries to parse that html string as json, causing it to throw a JSON.parse error. It wasn't clear that the parse error was related to the rate limit.

Would you want this module to handle that case? One suggestion would be to return a more descriptive error if the response status code is anything but 200, e.g.

```js
if (response && response.statusCode !== 200) {
  return callback(new Error('Non-200 statusCode from validator api'), null);
}
```

If that sounds good I can float a PR.

**Comment by sideshowbarker** [comment]
Yeah it sounds reasonable and I would welcome a PR to review

**Comment by sideshowbarker** [comment]
oh, I replied thinking this had been filed against the https://github.com/validator/validator sources

**Comment by sideshowbarker** [comment]
Sorry for the noise. Upon reflection, I guess there might not be anything I change with regard to this upstream in the validator sources themselves, and it needs to be handled in whatever frontends are being used on top of it. But if there is some useful change related this problem case that anybody imagines I might be able to make upstream, I would be happy to do that.

**Comment by danpaz** [comment]
Sorry if I wasn't clear with my explanation, but to clarify your response did you mean that you think this case should be handled by a layer above or below this module? I think it's reasonable to expect this module to let the consumer know if the http request was unsuccessful, and also not to try to parse html as json. Maybe I can make a PR to explain further and to get your feedback.

**Comment by sideshowbarker** [comment]
> did you mean that you think this case should be handled by a layer above or below this module?

After thinking about it only very briefly, I had thought that it might be possible to handle it differently in the layer above; but after some further consideration, I don’t really see how it could be. So think the appropriate place to instead handle it is at the layer of this module.
