### ISSUE TITLE
On fresh clone, tests fail

### ISSUE THREAD

**Issue by davidtheclark** [zrrrzzt/html-validator#62]
Was going to start on a PR for #57; but on a fresh clone, tests are failing. Here are the specific failures:

```
1) test/lib/html-validator-promises-test.js Returns error if invalid validator is specified test unfinished:
     Error: test unfinished
      at Object.<anonymous> (test/lib/html-validator-promises-test.js:33:5)

  2) test/lib/html-validator-promises-test.js child test left in queue Test: Requires options.url to be a valid url:
     child test left in queue Test: Requires options.url to be a valid url


  3) test/lib/html-validator-promises-test.js child test left in queue Test: Returns error if not status 200 OK:
     child test left in queue Test: Returns error if not status 200 OK


  4) test/lib/html-validator-promises-test.js child test left in queue Test: Should get 0 error messages from valid.html:
     child test left in queue Test: Should get 0 error messages from valid.html


  5) test/lib/html-validator-promises-test.js child test left in queue Test: Should get 1 error message from invalid.html:
     child test left in queue Test: Should get 1 error message from invalid.html


  6) test/lib/html-validator-promises-test.js child test left in queue Test: Should get 0 error messages from invalid.html if ignored:
     child test left in queue Test: Should get 0 error messages from invalid.html if ignored


  7) test/lib/html-validator-promises-test.js test count !== plan:

      test count !== plan
      + expected - actual

      -10
      +5



  8) test/lib/html-validator-test.js Validator not found:
     Error: Validator not found
      at test/lib/html-validator-test.js:31:9
      at Request.request [as _callback] (index.js:60:16)
```

**Comment by zrrrzzt** [comment]
Strange... as bugs usually are.

Which version of Node are you running?

I just did fresh clone and used nvm to test agains 4.8.3. All tests pass on my Mac.
[Travis](https://travis-ci.org/zrrrzzt/html-validator) seems OK as well.

If we could just find out a little more about your setup we might have a chance to solve this :-)

**Comment by davidtheclark** [comment]
I was using Node 6.11. Also tried Node 4.7.3. Didn't work in either, same error as above. Tried `rm -rf node_modules && npm install` a couple of times and still hit it. :|

**Comment by zrrrzzt** [comment]
Tested version 2.2.1 with 4.8.3, 6.11.0 and 8.1.3 and the newest version 2.2.2 with the same versions of Node. Still not able to reproduce your errors.

It seems like the test that fails is the one where I just use a non-existing url as [validator](https://github.com/zrrrzzt/html-validator/blob/master/test/lib/html-validator-test.js#L25)
I'm not sure if dns-providers solves this in different ways.

This test is really not that important so you could try to remove it or rewrite it.
Maybe it should not be in there at all.

**Comment by davidtheclark** [comment]
> It seems like the test that fails is the one where I just use a non-existing url as validator
I'm not sure if dns-providers solves this in different ways.

Yes, this is it exactly. Coincidentally, I ran into the same issue on another project and realized that my ISP's DNS server gives me a stupid error message that breaks these tests. I switched to a public DNS and the tests passed fine. Sorry for the confusion!
