### ISSUE TITLE
Ignores produce wrong console log

### ISSUE THREAD

**Issue by XhmikosR** [zrrrzzt/html-validator#67]
For example

```
From line 1106, column 9; to line 1106, column 86

The document validates according to the specified schema(s).
```

It shouldn't mention the first line at all if there's no other error apart from the ignored one(s).

**Comment by zrrrzzt** [comment]
@XhmikosR I need more information. What is the context of this console log?

**Comment by XhmikosR** [comment]
@zrrrzzt: I get this in the branch I switched to html-validator in Bootstrap https://github.com/twbs/bootstrap/pull/23327, see this for example https://travis-ci.org/twbs/bootstrap/jobs/264631104

**Comment by XhmikosR** [comment]
That was fast, thanks!

I'll wait for a new release and test things out.

**Comment by zrrrzzt** [comment]
@XhmikosR hope this one works out for you :-) It's out on npm as well now

**Comment by XhmikosR** [comment]
Yeah, I still need to fix my implementation. :/

Current with `async.eachLimit` the first 10 instances are run asynchronous so the validator results seem random.
